services:
  - type: web
    name: your-backend-service
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGODB_URI
        value: your_mongodb_uri
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000
